### ISSUE TITLE
Missing ~/Library/Containers/com.bohemiancoding.sketch3 folder?

### ISSUE THREAD

**Issue by arturnbull** [RayPS/my-sketch-colors#1]
Hey Ray,

This looks great. Just trying to set it up but your terminal commands don't seem to work with my setup.  I looked and I don't have a ~/Library/Containers/com.bohemiancoding.sketch3 folder. Any idea where this might be?

Thanks!

**Comment by RayPS** [comment]
Oops,
I tested it on 3 Macs and my friend's Mac it works.
But there is a way to find out the problem.
Let's click the menu item "Plugins > Reveal Plugins Folder" in Sketch, then tell me the path of this folder.

**Comment by RayPS** [comment]
Hey, are you using the AppStore version or out of AppStore?

**Comment by RayPS** [comment]
Thank you, your issue is helpful, give me a minutes i'll fix this.

**Comment by arturnbull** [comment]
Ahh thanks.  I should be able to take it from here. :+1: 
(you're right, it wasn't through the App Store)

FYI the path is Library ▸ Application Support ▸ com.bohemiancoding.sketch3

**Comment by RayPS** [comment]
It's okay now, read the introductions again, thank you! @arturnbull
