### ISSUE TITLE
Doesn't work with Sketch 3.3

### ISSUE THREAD

**Issue by tinhspace** [RayPS/my-sketch-colors#3]
Hello RayPS,
I installed your plugin but it doesn't work with Sketch 3.3 (11970). Do you test it with new Sketch version 3.3 ? 

My Sketch Plugin folder:

![image](https://cloud.githubusercontent.com/assets/236967/7040800/e44e0d22-ddfc-11e4-849d-eee3a2e825d9.png)

**Comment by alexeiboronnikov** [comment]
Same here. Doesn't work with Beta 3.3

**Comment by RayPS** [comment]
@alexeiboronnikov @aresta Fixed! Thank you!

**Comment by alexeiboronnikov** [comment]
Still the same.

**Comment by RayPS** [comment]
@alexeiboronnikov Are you using the commands to install it?

**Comment by alexeiboronnikov** [comment]
tried all three ways :(
i'm on Beta 3.3

**Comment by RayPS** [comment]
@alexeiboronnikov Oh Beta! I will update an installation for beta, give me a sec.

**Comment by RayPS** [comment]
@alexeiboronnikov Updated, read the introductions again, let me know if it works.

**Comment by alexeiboronnikov** [comment]
@RayPS cheers buddy! it works now :)

**Comment by tinhspace** [comment]
Work like a charm !!! Thank you so much.

![image](https://cloud.githubusercontent.com/assets/236967/7042978/f43a1628-de0f-11e4-98eb-19f7c4d6a764.png)

**Comment by RayPS** [comment]
@aresta @alexeiboronnikov  Glad to hear that :smiley:  Thanks so much guys!
