### ISSUE TITLE
How did you create a preset?

### ISSUE THREAD

**Issue by gabrieltomescu** [RayPS/my-sketch-colors#4]
I've been looking everywhere for this! How did you create a sketchpreset file?

**Comment by RayPS** [comment]
https://github.com/RayPS/my-sketch-colors/wiki/Create-your-own-preset

**Comment by gabrieltomescu** [comment]
I see. So Sketch always generates this file. Cool, thanks.

**Comment by RayPS** [comment]
Yes, it saves when Sketch is quitting.
