### ISSUE TITLE
Not working for 3.4.2

### ISSUE THREAD

**Issue by alexcamlo** [RayPS/my-sketch-colors#7]
Hi, I seen putting the file **assets-v55.sketchpreset** into the **com.bohemiancoding.sketch3** folder doesnt' work anymore.
I've seen there are two more sketchpreset files at the forlder **assets-v60** and **assets-v62**.
I've tried changing **assets-v55** name to this other two and doesn't work.

**Comment by RayPS** [comment]
Just updated, can you try it again? Thanks!

**Comment by alexcamlo** [comment]
Worked but had to change the name to **assets-v60.sketchpreset**

I have de MAS version, don't know if that affects something.

**Comment by RayPS** [comment]
1aea11a7b83cc6079317dbf5881e1d844a9dafd7
