### ISSUE TITLE
Doesn't work in Sketch 3.4 anymore

### ISSUE THREAD

**Issue by edge0703** [RayPS/my-sketch-colors#8]
Really love your plugin, but unfortunately it doesn't work anymore in Sketch (final and beta), neither manually nor automatically.

**Comment by margox** [comment]
Aha,I encountered the same problem before,but now it's work for me. Check the "com.bohemiancoding.sketch3" folder, can you find anthor file named "assets-vXX.sketchpreset" in this folder? (ps:the XX can be 62 or 61 or some number else),but the file you downloaded from this repository is named "assets-v60.sketchpreset",just quit your Sketch and backup the file "assets-vXX.sketchpreset" and then rename the "assets-v60.sketchpreset" correctly, launch your Sketch, you'll see the colors, good luck!

**Comment by edge0703** [comment]
Worked, thanks for the help!
