### ISSUE TITLE
Issue ?

### ISSUE THREAD

**Issue by ivancucer** [RayPS/my-sketch-colors#9]
Hello,

Hmm... nothing happens in version 3.5.2 ...

Best,
Ivan

**Comment by alexcamlo** [comment]
Hi @ivancucer,
Sometimes the numbers of the file change.
If you go to the folder ~/Library/Application Support/com.bohemiancoding.sketch3 you'll see several asset-v*.sketchpreset files… In my case I have *-v62, *-v63, *-v76, *-v78. Maybe try replacing some other of this files (but remember backing up the original file).

**Comment by RayPS** [comment]
Just updated for 3.6.2 in e246d77

**Comment by ivancucer** [comment]
Perfect! Thank you man
